name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #add step checkout
      - name: Checkout code
        uses: actions/checkout@v3
      #The actions/checkout@v3 step retrieves your repository files (including pom.xml) 
      #into the runner's workspace at /home/runner/work/Bai10/Bai10,
      # allowing Maven to locate and use the project configuration.
      #fix error "The goal you specified requires a project to execute but there is no POM in this directory"
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn package

